### ISSUE TITLE
ValueError: <AuthenticationType.EXTERNAL: 'external'> is not a valid AuthenticationMethod

### ISSUE THREAD

**Issue by rouke-broersma** [buildarr/buildarr-prowlarr#34]
According to the docs AuthenticationMethod should be set to External if authentication should be disabled but this value is not supported by buildarr.

https://wiki.servarr.com/prowlarr/faq#authentication-method

Note that this value comes from the remote config and is accepted by prowlarr:

```
2023-11-05 14:38:37,349 buildarr:1 buildarr.cli.daemon [INFO] Buildarr version 0.6.1 (log level: INFO)
2023-11-05 14:38:37,349 buildarr:1 buildarr.cli.daemon [INFO] Loading configuration file '/config/buildarr.yml'
2023-11-05 14:38:37,377 buildarr:1 buildarr.cli.daemon [INFO] Finished loading configuration file
2023-11-05 14:38:37,377 buildarr:1 buildarr.cli.daemon [INFO] Daemon configuration:
2023-11-05 14:38:37,377 buildarr:1 buildarr.cli.daemon [INFO]  - Watch configuration files: Yes
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]  - Configuration files to watch:
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]    - /config/buildarr.yml
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]    - /prowlarr/prowlarr.yaml
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]  - Update at:
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]    - Monday 03:00
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]    - Tuesday 03:00
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]    - Wednesday 03:00
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]    - Thursday 03:00
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]    - Friday 03:00
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]    - Saturday 03:00
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO]    - Sunday 03:00
2023-11-05 14:38:37,378 buildarr:1 buildarr.cli.daemon [INFO] Scheduling update jobs
2023-11-05 14:38:37,379 buildarr:1 buildarr.cli.daemon [INFO] Finished scheduling update jobs
2023-11-05 14:38:37,379 buildarr:1 buildarr.cli.daemon [INFO] Enabling config file monitoring
2023-11-05 14:38:37,379 buildarr:1 buildarr.cli.daemon [INFO] Finished enabling config file monitoring
2023-11-05 14:38:37,379 buildarr:1 buildarr.cli.daemon [INFO] Applying initial configuration
2023-11-05 14:38:37,386 buildarr:1 buildarr.cli.run [INFO] Loaded plugins: jellyseerr (0.2.0), prowlarr (0.4.0), radarr (0.1.1), sonarr (0.5.4)
2023-11-05 14:38:37,386 buildarr:1 buildarr.cli.run [INFO] Loading instance configurations
2023-11-05 14:38:37,387 buildarr:1 buildarr.cli.run [INFO] Finished loading instance configurations
2023-11-05 14:38:37,387 buildarr:1 buildarr.cli.run [INFO] Running with plugins: prowlarr
2023-11-05 14:38:37,388 buildarr:1 buildarr.cli.run [INFO] Resolving instance dependencies
2023-11-05 14:38:37,388 buildarr:1 buildarr.cli.run [INFO] Finished resolving instance dependencies
2023-11-05 14:38:37,388 buildarr:1 buildarr.cli.run [INFO] Rendering instance configuration dynamic attributes
2023-11-05 14:38:37,388 buildarr:1 buildarr.cli.run [INFO] Finished rendering instance configuration dynamic attributes
2023-11-05 14:38:37,388 buildarr:1 buildarr.cli.run [INFO] Loading secrets file from '/secrets/secrets.json'
2023-11-05 14:38:37,389 buildarr:1 buildarr.cli.run [INFO] Finished loading secrets file
2023-11-05 14:38:37,389 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Checking secrets
2023-11-05 14:38:37,393 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Connection test successful using cached secrets
2023-11-05 14:38:37,393 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Finished checking secrets
2023-11-05 14:38:37,393 buildarr:1 buildarr.cli.run [INFO] Saving updated secrets file to '/secrets/secrets.json'
2023-11-05 14:38:37,394 buildarr:1 buildarr.cli.run [INFO] Finished saving updated secrets file
2023-11-05 14:38:37,394 buildarr:1 buildarr.cli.run [INFO] Performing post-initialisation configuration render
2023-11-05 14:38:37,394 buildarr:1 buildarr.cli.run [INFO] Finished performing post-initialisation configuration render
2023-11-05 14:38:37,394 buildarr:1 buildarr.cli.run [INFO] Updating configuration on remote instances
2023-11-05 14:38:37,394 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Fetching remote configuration to check if updates are required
Traceback (most recent call last):
  File "/usr/local/bin/buildarr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 568, in daemon
    ).start()
      ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 113, in start
    self._initial_run()
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 226, in _initial_run
    run_apply(secrets_file_path=self._secrets_file_path)
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 287, in _run
    remote_instance_config = manager.from_remote(instance_config, instance_secrets)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 171, in from_remote
    return instance_config.from_remote(secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/__init__.py", line 157, in from_remote
    settings=ProwlarrSettings.from_remote(secrets),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
    fields[field_name] = field.type_.from_remote(secrets)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/settings/general.py", line 585, in from_remote
    security=SecurityGeneralSettings._from_remote(remote_attrs),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/settings/general.py", line 107, in _from_remote
    return cls(**cls.get_local_attrs(cls._remote_map, remote_attrs))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 243, in get_local_attrs
    local_attrs[attr_name] = decoder(remote_attr)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 195, in <lambda>
    lambda v: cls._decode_attr(attr_name, v),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 714, in _decode_attr
    return cls._decode_attr_(cls.__fields__[attr_name].outer_type_, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 740, in _decode_attr_
    return type_tree[-1](value)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: <AuthenticationType.EXTERNAL: 'external'> is not a valid AuthenticationMethod
```

**Comment by Callum027** [comment]
Thanks for bringing this to my attention. You're right, it looks like I neglected to add support for the `external` authentication type.

**Comment by Callum027** [comment]
https://github.com/buildarr/buildarr-prowlarr/pull/37

**Comment by Callum027** [comment]
https://github.com/buildarr/buildarr-prowlarr/pull/38

**Comment by Callum027** [comment]
Thanks for waiting. the fix for this issue has been released as:

* Python package: `buildarr-prowlarr==0.4.2`
* Docker container: `callum027/buildarr:0.6.5`

Please give the new version a try to check that it resolves your issue.

**Comment by rouke-broersma** [comment]
Works :)
