### ISSUE TITLE
Radarr app setting create: TypeError: 'ApplicationResource' object is not a mapping

### ISSUE THREAD

**Issue by rouke-broersma** [buildarr/buildarr-prowlarr#35]
While trying to create the radarr app setting in prowlarr I'm getting the following error:

```
2023-11-05 14:42:11,944 buildarr:1 buildarr.cli.daemon [INFO] Buildarr version 0.6.1 (log level: INFO)
2023-11-05 14:42:11,944 buildarr:1 buildarr.cli.daemon [INFO] Loading configuration file '/config/buildarr.yml'
2023-11-05 14:42:11,972 buildarr:1 buildarr.cli.daemon [INFO] Finished loading configuration file
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO] Daemon configuration:
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]  - Watch configuration files: Yes
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]  - Configuration files to watch:
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]    - /config/buildarr.yml
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]    - /prowlarr/prowlarr.yaml
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]  - Update at:
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]    - Monday 03:00
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]    - Tuesday 03:00
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]    - Wednesday 03:00
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]    - Thursday 03:00
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]    - Friday 03:00
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]    - Saturday 03:00
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO]    - Sunday 03:00
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO] Scheduling update jobs
2023-11-05 14:42:11,973 buildarr:1 buildarr.cli.daemon [INFO] Finished scheduling update jobs
2023-11-05 14:42:11,974 buildarr:1 buildarr.cli.daemon [INFO] Enabling config file monitoring
2023-11-05 14:42:11,974 buildarr:1 buildarr.cli.daemon [INFO] Finished enabling config file monitoring
2023-11-05 14:42:11,974 buildarr:1 buildarr.cli.daemon [INFO] Applying initial configuration
2023-11-05 14:42:11,981 buildarr:1 buildarr.cli.run [INFO] Loaded plugins: jellyseerr (0.2.0), prowlarr (0.4.0), radarr (0.1.1), sonarr (0.5.4)
2023-11-05 14:42:11,981 buildarr:1 buildarr.cli.run [INFO] Loading instance configurations
2023-11-05 14:42:11,983 buildarr:1 buildarr.cli.run [INFO] Finished loading instance configurations
2023-11-05 14:42:11,983 buildarr:1 buildarr.cli.run [INFO] Running with plugins: prowlarr
2023-11-05 14:42:11,983 buildarr:1 buildarr.cli.run [INFO] Resolving instance dependencies
2023-11-05 14:42:11,983 buildarr:1 buildarr.cli.run [INFO] Finished resolving instance dependencies
2023-11-05 14:42:11,983 buildarr:1 buildarr.cli.run [INFO] Rendering instance configuration dynamic attributes
2023-11-05 14:42:11,983 buildarr:1 buildarr.cli.run [INFO] Finished rendering instance configuration dynamic attributes
2023-11-05 14:42:11,983 buildarr:1 buildarr.cli.run [INFO] Loading secrets file from '/secrets/secrets.json'
2023-11-05 14:42:11,984 buildarr:1 buildarr.cli.run [INFO] Secrets file does not exist, will create new file
2023-11-05 14:42:11,984 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Checking secrets
2023-11-05 14:42:11,984 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Connection test failed using cached secrets (or not cached), fetching secrets
2023-11-05 14:42:11,988 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Connection test successful using fetched secrets
2023-11-05 14:42:11,988 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Finished checking secrets
2023-11-05 14:42:11,988 buildarr:1 buildarr.cli.run [INFO] Saving updated secrets file to '/secrets/secrets.json'
2023-11-05 14:42:11,989 buildarr:1 buildarr.cli.run [INFO] Finished saving updated secrets file
2023-11-05 14:42:11,989 buildarr:1 buildarr.cli.run [INFO] Performing post-initialisation configuration render
2023-11-05 14:42:11,989 buildarr:1 buildarr.cli.run [INFO] Finished performing post-initialisation configuration render
2023-11-05 14:42:11,989 buildarr:1 buildarr.cli.run [INFO] Updating configuration on remote instances
2023-11-05 14:42:11,989 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Fetching remote configuration to check if updates are required
2023-11-05 14:42:12,036 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Finished fetching remote configuration
2023-11-05 14:42:12,044 buildarr:1 buildarr.cli.run [INFO] <prowlarr> (default) Updating remote configuration
2023-11-05 14:42:12,060 buildarr:1 buildarr.config.base [INFO] <prowlarr> (default) prowlarr.settings.apps.applications.definitions['Radarr'].prowlarr_url: 'http://prowlarr.prowlarr' -> (created)
2023-11-05 14:42:12,060 buildarr:1 buildarr.config.base [INFO] <prowlarr> (default) prowlarr.settings.apps.applications.definitions['Radarr'].base_url: 'http://radarr.radarr' -> (created)
2023-11-05 14:42:12,060 buildarr:1 buildarr.config.base [INFO] <prowlarr> (default) prowlarr.settings.apps.applications.definitions['Radarr'].sync_level: 'full-sync' -> (created)
2023-11-05 14:42:12,060 buildarr:1 buildarr.config.base [INFO] <prowlarr> (default) prowlarr.settings.apps.applications.definitions['Radarr'].sync_categories: {'movies/sd', 'movies/hd', 'movies/other', 'movies/foreign', 'movies', 'movies/dvd', 'movies/bluray', 'movies/uhd', 'movies/web-dl', 'movies/3d'} -> (created)
2023-11-05 14:42:12,060 buildarr:1 buildarr.config.base [INFO] <prowlarr> (default) prowlarr.settings.apps.applications.definitions['Radarr'].tags: set() -> (created)
2023-11-05 14:42:12,060 buildarr:1 buildarr.config.base [INFO] <prowlarr> (default) prowlarr.settings.apps.applications.definitions['Radarr'].api_key: '**********' -> (created)
Traceback (most recent call last):
  File "/usr/local/bin/buildarr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 568, in daemon
    ).start()
      ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 113, in start
    self._initial_run()
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 226, in _initial_run
    run_apply(secrets_file_path=self._secrets_file_path)
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 300, in _run
    if manager.update_remote(
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 192, in update_remote
    return local_instance_config.update_remote(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 272, in update_remote
    if isinstance(field, ConfigBase) and field.update_remote(
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/settings/__init__.py", line 70, in update_remote
    self.apps.update_remote(
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 272, in update_remote
    if isinstance(field, ConfigBase) and field.update_remote(
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/settings/apps/applications.py", line 740, in update_remote
    local_application._create_remote(
  File "/usr/local/lib/python3.11/site-packages/buildarr_prowlarr/config/settings/apps/applications.py", line 207, in _create_remote
    remote_attrs = {"name": application_name, **api_schema, **set_attrs}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'ApplicationResource' object is not a mapping
```

Note that no application is created in Prowlarr. Does radarr actually need to exist for the config the successfully push? I know this is required in the Prowlarr UI but I hoped this would not be the case through buildarr/ the api.

**Comment by Callum027** [comment]
This appears to be a regression from a fix made in the latest release. Thanks for pointing it out.

> Note that no application is created in Prowlarr. Does radarr actually need to exist for the config the successfully push? I know this is required in the Prowlarr UI but I hoped this would not be the case through buildarr/ the api.

No, Buildarr will create it if it does not exist. As long as the Radarr instance itself exists and is running, Buildarr should configure Prowlarr to manage it.

**Comment by rouke-broersma** [comment]
> This appears to be a regression from a fix made in the latest release. Thanks for pointing it out.
> 
> > Note that no application is created in Prowlarr. Does radarr actually need to exist for the config the successfully push? I know this is required in the Prowlarr UI but I hoped this would not be the case through buildarr/ the api.
> 
> No, Buildarr will create it if it does not exist. As long as the Radarr instance itself exists and is running, Buildarr should configure Prowlarr to manage it.

And if my radarr instance is not yet running? Does buildarr then fail?

**Comment by Callum027** [comment]
> And if my radarr instance is not yet running? Does buildarr then fail?

Yes. Prowlarr performs a connection check to the Radarr instance when the application is created in Prowlarr, so it will return an error if it couldn't connect.

You *don't* need the Radarr instance managed by Buildarr in order to configure its connection to Prowlarr through Buildarr. If you can just start the Radarr instance and get its API key, you can [add the Radarr API key](https://buildarr.github.io/plugins/prowlarr/configuration/settings/apps/applications/#buildarr_prowlarr.config.settings.apps.applications.RadarrApplication.api_key) to the configuration and you can make Prowlarr connect to it.

**Comment by Callum027** [comment]
https://github.com/buildarr/buildarr-prowlarr/pull/39

**Comment by Callum027** [comment]
Thanks for waiting. the fix for this issue has been released as:

* Python package: `buildarr-prowlarr==0.4.2`
* Docker container: `callum027/buildarr:0.6.5`

Please give the new version a try to check that it resolves your issue.

**Comment by Callum027** [comment]
A regression from the above release has been fixed, and released as:

* Python package: `buildarr-prowlarr==0.4.3`
* Docker container: `callum027/buildarr:0.6.6`

Please give the new version a try.

**Comment by rouke-broersma** [comment]
Have managed to setup sonarr and prowlarr with buildarr so far so I'm pretty sure this is fixed for radarr as well :)
